#!/bin/sh
#ddev-generated
## Description: Run redis-cli inside the redis container
## Usage: redis [flags] [args]
## Example: "redis KEYS *" or "ddev redis-cli INFO" or "ddev redis-cli --version"

redis-cli -p 6379 -h redis -a redis --no-auth-warning "$@"
