http:
  routers:
    next-drupal-starterkit-elasticvue-8080-http:
      entrypoints:
        - http-9005
      rule: HostRegexp(`^next-drupal-starterkit\.ddev\.site$`)|| HostRegexp(`^frontend\.ddev\.site$`)
      
      service: "next-drupal-starterkit-elasticvue-8080"
      tls: false
      # middlewares:
      #   - "next-drupal-starterkit-redirectHttps"
    next-drupal-starterkit-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^next-drupal-starterkit\.ddev\.site$`)|| HostRegexp(`^frontend\.ddev\.site$`)
      
      service: "next-drupal-starterkit-web-80"
      tls: false
      # middlewares:
      #   - "next-drupal-starterkit-redirectHttps"
    next-drupal-starterkit-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^next-drupal-starterkit\.ddev\.site$`)|| HostRegexp(`^frontend\.ddev\.site$`)
      
      service: "next-drupal-starterkit-web-8025"
      tls: false
      # middlewares:
      #   - "next-drupal-starterkit-redirectHttps"
    next-drupal-starterkit-web-3000-http:
      entrypoints:
        - http-3000
      rule: HostRegexp(`^next-drupal-starterkit\.ddev\.site$`)|| HostRegexp(`^frontend\.ddev\.site$`)
      
      service: "next-drupal-starterkit-web-3000"
      tls: false
      # middlewares:
      #   - "next-drupal-starterkit-redirectHttps"
    next-drupal-starterkit-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^next-drupal-starterkit\.ddev\.site$`)|| HostRegexp(`^frontend\.ddev\.site$`)
      
      service: "next-drupal-starterkit-xhgui-80"
      tls: false
      # middlewares:
      #   - "next-drupal-starterkit-redirectHttps"
    next-drupal-starterkit-elasticsearch-9200-http:
      entrypoints:
        - http-9200
      rule: HostRegexp(`^next-drupal-starterkit\.ddev\.site$`)|| HostRegexp(`^frontend\.ddev\.site$`)
      
      service: "next-drupal-starterkit-elasticsearch-9200"
      tls: false
      # middlewares:
      #   - "next-drupal-starterkit-redirectHttps"

    ### START OF CUSTOM ROUTERS ADDITIONS
    next-drupal-starterkit-web-80-http-frontend:
      entrypoints:
        - http-80
      rule: Host(`frontend.ddev.site`)
      service: "next-drupal-starterkit-web-node-3000"
      ruleSyntax: v3
      tls: false
      priority: 100

    # Router for HTTPS (port 443)
    next-drupal-starterkit-web-80-https-frontend:
      entrypoints:
        - http-443
      rule: Host(`frontend.ddev.site`)
      service: "next-drupal-starterkit-web-node-3000"
      ruleSyntax: v3
      tls: true
      priority: 100

    ### END OF CUSTOM ROUTERS ADDITIONS
    
    next-drupal-starterkit-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^next-drupal-starterkit\.ddev\.site$`) || HostRegexp(`^frontend\.ddev\.site$`)
      
      service: "next-drupal-starterkit-web-80"
      
      tls: true

    next-drupal-starterkit-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^next-drupal-starterkit\.ddev\.site$`) || HostRegexp(`^frontend\.ddev\.site$`)
      
      service: "next-drupal-starterkit-web-8025"
      
      tls: true

    next-drupal-starterkit-web-3000-https:
      entrypoints:
        - http-3001
      rule: HostRegexp(`^next-drupal-starterkit\.ddev\.site$`) || HostRegexp(`^frontend\.ddev\.site$`)
      
      service: "next-drupal-starterkit-web-3000"
      
      tls: true

    
    next-drupal-starterkit-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^next-drupal-starterkit\.ddev\.site$`) || HostRegexp(`^frontend\.ddev\.site$`)
      
      service: "next-drupal-starterkit-xhgui-80"
      
      tls: true

    
    next-drupal-starterkit-elasticsearch-9200-https:
      entrypoints:
        - http-9201
      rule: HostRegexp(`^next-drupal-starterkit\.ddev\.site$`) || HostRegexp(`^frontend\.ddev\.site$`)
      
      service: "next-drupal-starterkit-elasticsearch-9200"
      
      tls: true



  middlewares:
    next-drupal-starterkit-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    next-drupal-starterkit-elasticvue-8080:
      loadbalancer:
        servers:
          - url: http://ddev-next-drupal-starterkit-elasticvue:8080

    next-drupal-starterkit-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-next-drupal-starterkit-web:80

    next-drupal-starterkit-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-next-drupal-starterkit-web:8025
    ### START OF CUSTOM SERVICES ADDITIONS
    next-drupal-starterkit-web-3000:
      loadbalancer:
        servers:
          - url: http://ddev-next-drupal-starterkit-web:3000

    ### END OF CUSTOM SERVICES ADDITIONS
    
    
    next-drupal-starterkit-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-next-drupal-starterkit-xhgui:80

    
    next-drupal-starterkit-elasticsearch-9200:
      loadbalancer:
        servers:
          - url: http://ddev-next-drupal-starterkit-elasticsearch:9200

    next-drupal-starterkit-web-node-3000:
      loadbalancer:
        servers:
          - url: http://next-drupal-starterkit.ddev.site:3000




tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/next-drupal-starterkit.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/next-drupal-starterkit.key