/* eslint-disable */
/* prettier-ignore */

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  query: 'Query';
  mutation: 'Mutation';
  subscription: never;
  types: {
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'info': { name: 'info'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SchemaInformation'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'UNION'; name: 'NodeUnion'; ofType: null; } }; 'media': { name: 'media'; type: { kind: 'UNION'; name: 'MediaUnion'; ofType: null; } }; 'menu': { name: 'menu'; type: { kind: 'OBJECT'; name: 'Menu'; ofType: null; } }; 'viewer': { name: 'viewer'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; 'nodeArticles': { name: 'nodeArticles'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NodeArticleConnection'; ofType: null; }; } }; 'nodePages': { name: 'nodePages'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NodePageConnection'; ofType: null; }; } }; 'mediaAudioItems': { name: 'mediaAudioItems'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaAudioConnection'; ofType: null; }; } }; 'mediaDocuments': { name: 'mediaDocuments'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaDocumentConnection'; ofType: null; }; } }; 'mediaImages': { name: 'mediaImages'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaImageConnection'; ofType: null; }; } }; 'mediaRemoteVideos': { name: 'mediaRemoteVideos'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaRemoteVideoConnection'; ofType: null; }; } }; 'mediaVideos': { name: 'mediaVideos'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaVideoConnection'; ofType: null; }; } }; 'route': { name: 'route'; type: { kind: 'UNION'; name: 'RouteUnion'; ofType: null; } }; 'articlesView': { name: 'articlesView'; type: { kind: 'OBJECT'; name: 'ArticlesViewResult'; ofType: null; } }; }; };
    'SchemaInformation': { kind: 'OBJECT'; name: 'SchemaInformation'; fields: { 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'home': { name: 'home'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'version': { name: 'version'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'languages': { name: 'languages'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; }; }; } }; }; };
    'String': unknown;
    'Language': { kind: 'OBJECT'; name: 'Language'; fields: { 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'direction': { name: 'direction'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'ID': unknown;
    'NodeUnion': { kind: 'UNION'; name: 'NodeUnion'; fields: {}; possibleTypes: 'NodeArticle' | 'NodeFrontpage' | 'NodePage'; };
    'NodeArticle': { kind: 'OBJECT'; name: 'NodeArticle'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'author': { name: 'author'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; 'body': { name: 'body'; type: { kind: 'OBJECT'; name: 'TextSummary'; ofType: null; } }; 'changed': { name: 'changed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'excerpt': { name: 'excerpt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'image': { name: 'image'; type: { kind: 'OBJECT'; name: 'Image'; ofType: null; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'metatag': { name: 'metatag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MetaTagUnion'; ofType: null; }; }; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'promote': { name: 'promote'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'sticky': { name: 'sticky'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'tags': { name: 'tags'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UnsupportedType'; ofType: null; }; }; } }; 'title': { name: 'title'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'translations': { name: 'translations'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Translation'; ofType: null; }; }; }; } }; }; };
    'NodeInterface': { kind: 'INTERFACE'; name: 'NodeInterface'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'author': { name: 'author'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; 'changed': { name: 'changed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'metatag': { name: 'metatag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MetaTagUnion'; ofType: null; }; }; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'promote': { name: 'promote'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'sticky': { name: 'sticky'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'title': { name: 'title'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; possibleTypes: 'NodeArticle' | 'NodeFrontpage' | 'NodePage'; };
    'User': { kind: 'OBJECT'; name: 'User'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'changed': { name: 'changed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'mail': { name: 'mail'; type: { kind: 'SCALAR'; name: 'Email'; ofType: null; } }; 'metatag': { name: 'metatag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MetaTagUnion'; ofType: null; }; }; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'roles': { name: 'roles'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'UserRoles'; ofType: null; }; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'UserStatus'; ofType: null; }; } }; }; };
    'UserInterface': { kind: 'INTERFACE'; name: 'UserInterface'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'changed': { name: 'changed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'mail': { name: 'mail'; type: { kind: 'SCALAR'; name: 'Email'; ofType: null; } }; 'metatag': { name: 'metatag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MetaTagUnion'; ofType: null; }; }; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'roles': { name: 'roles'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'UserRoles'; ofType: null; }; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'UserStatus'; ofType: null; }; } }; }; possibleTypes: 'User'; };
    'DateTime': { kind: 'OBJECT'; name: 'DateTime'; fields: { 'timestamp': { name: 'timestamp'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Timestamp'; ofType: null; }; } }; 'timezone': { name: 'timezone'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'TimeZone'; ofType: null; }; } }; 'offset': { name: 'offset'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'UtcOffset'; ofType: null; }; } }; 'time': { name: 'time'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Time'; ofType: null; }; } }; }; };
    'Timestamp': unknown;
    'TimeZone': unknown;
    'UtcOffset': unknown;
    'Time': unknown;
    'Email': unknown;
    'MetaTagUnion': { kind: 'UNION'; name: 'MetaTagUnion'; fields: {}; possibleTypes: 'MetaTagLink' | 'MetaTagValue' | 'MetaTagProperty' | 'MetaTagScript'; };
    'MetaTagLink': { kind: 'OBJECT'; name: 'MetaTagLink'; fields: { 'tag': { name: 'tag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'attributes': { name: 'attributes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MetaTagLinkAttributes'; ofType: null; }; } }; }; };
    'MetaTag': { kind: 'INTERFACE'; name: 'MetaTag'; fields: { 'tag': { name: 'tag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; possibleTypes: 'MetaTagLink' | 'MetaTagValue' | 'MetaTagProperty' | 'MetaTagScript'; };
    'MetaTagLinkAttributes': { kind: 'OBJECT'; name: 'MetaTagLinkAttributes'; fields: { 'href': { name: 'href'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'hreflang': { name: 'hreflang'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'rel': { name: 'rel'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'media': { name: 'media'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'sizes': { name: 'sizes'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'type': { name: 'type'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'MetaTagValue': { kind: 'OBJECT'; name: 'MetaTagValue'; fields: { 'tag': { name: 'tag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'attributes': { name: 'attributes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MetaTagValueAttributes'; ofType: null; }; } }; }; };
    'MetaTagValueAttributes': { kind: 'OBJECT'; name: 'MetaTagValueAttributes'; fields: { 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'content': { name: 'content'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'MetaTagProperty': { kind: 'OBJECT'; name: 'MetaTagProperty'; fields: { 'tag': { name: 'tag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'attributes': { name: 'attributes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MetaTagPropertyAttributes'; ofType: null; }; } }; }; };
    'MetaTagPropertyAttributes': { kind: 'OBJECT'; name: 'MetaTagPropertyAttributes'; fields: { 'property': { name: 'property'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'content': { name: 'content'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'MetaTagScript': { kind: 'OBJECT'; name: 'MetaTagScript'; fields: { 'tag': { name: 'tag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'attributes': { name: 'attributes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MetaTagScriptAttributes'; ofType: null; }; } }; 'content': { name: 'content'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'MetaTagScriptAttributes': { kind: 'OBJECT'; name: 'MetaTagScriptAttributes'; fields: { 'type': { name: 'type'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'src': { name: 'src'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'integrity': { name: 'integrity'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'UserRoles': unknown;
    'UserStatus': { kind: 'ENUM'; name: 'UserStatus'; type: 'ACTIVE' | 'BLOCKED'; };
    'MetaTagInterface': { kind: 'INTERFACE'; name: 'MetaTagInterface'; fields: { 'metatag': { name: 'metatag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MetaTagUnion'; ofType: null; }; }; }; } }; }; possibleTypes: 'NodeArticle' | 'User' | 'NodeFrontpage' | 'MediaImage' | 'MediaDocument' | 'MediaRemoteVideo' | 'MediaVideo' | 'NodePage' | 'MediaAudio'; };
    'Boolean': unknown;
    'EdgeNode': { kind: 'INTERFACE'; name: 'EdgeNode'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; possibleTypes: 'NodeArticle' | 'MediaImage' | 'MediaDocument' | 'MediaRemoteVideo' | 'MediaVideo' | 'NodePage' | 'MediaAudio'; };
    'TextSummary': { kind: 'OBJECT'; name: 'TextSummary'; fields: { 'value': { name: 'value'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'processed': { name: 'processed'; type: { kind: 'SCALAR'; name: 'Html'; ofType: null; } }; 'format': { name: 'format'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'summary': { name: 'summary'; type: { kind: 'SCALAR'; name: 'Html'; ofType: null; } }; }; };
    'Html': unknown;
    'Image': { kind: 'OBJECT'; name: 'Image'; fields: { 'url': { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'width': { name: 'width'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'height': { name: 'height'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'alt': { name: 'alt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'title': { name: 'title'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'size': { name: 'size'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'mime': { name: 'mime'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'Int': unknown;
    'UnsupportedType': { kind: 'OBJECT'; name: 'UnsupportedType'; fields: { 'unsupported': { name: 'unsupported'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; }; };
    'Translation': { kind: 'OBJECT'; name: 'Translation'; fields: { 'title': { name: 'title'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'path': { name: 'path'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'NodeFrontpage': { kind: 'OBJECT'; name: 'NodeFrontpage'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'author': { name: 'author'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; 'changed': { name: 'changed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'contentElements': { name: 'contentElements'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'NodeFrontpageContentElementsUnion'; ofType: null; }; }; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'excerpt': { name: 'excerpt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'image': { name: 'image'; type: { kind: 'OBJECT'; name: 'Image'; ofType: null; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'metatag': { name: 'metatag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MetaTagUnion'; ofType: null; }; }; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'promote': { name: 'promote'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'sticky': { name: 'sticky'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'title': { name: 'title'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'translations': { name: 'translations'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Translation'; ofType: null; }; }; }; } }; }; };
    'NodeFrontpageContentElementsUnion': { kind: 'UNION'; name: 'NodeFrontpageContentElementsUnion'; fields: {}; possibleTypes: 'ParagraphHero' | 'ParagraphFormattedText' | 'ParagraphImage' | 'ParagraphLink' | 'ParagraphAccordion' | 'ParagraphVideo' | 'ParagraphListingArticle' | 'ParagraphFileAttachment'; };
    'ParagraphHero': { kind: 'OBJECT'; name: 'ParagraphHero'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'formattedText': { name: 'formattedText'; type: { kind: 'OBJECT'; name: 'Text'; ofType: null; } }; 'heading': { name: 'heading'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'image': { name: 'image'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaImage'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'primaryLink': { name: 'primaryLink'; type: { kind: 'OBJECT'; name: 'Link'; ofType: null; } }; 'secondaryLink': { name: 'secondaryLink'; type: { kind: 'OBJECT'; name: 'Link'; ofType: null; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'ParagraphInterface': { kind: 'INTERFACE'; name: 'ParagraphInterface'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; possibleTypes: 'ParagraphHero' | 'ParagraphFormattedText' | 'ParagraphImage' | 'ParagraphLink' | 'ParagraphAccordion' | 'ParagraphAccordionItem' | 'ParagraphFileAttachment' | 'ParagraphVideo' | 'ParagraphListingArticle'; };
    'Text': { kind: 'OBJECT'; name: 'Text'; fields: { 'value': { name: 'value'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'processed': { name: 'processed'; type: { kind: 'SCALAR'; name: 'Html'; ofType: null; } }; 'format': { name: 'format'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'MediaImage': { kind: 'OBJECT'; name: 'MediaImage'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'changed': { name: 'changed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'mediaImage': { name: 'mediaImage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Image'; ofType: null; }; } }; 'metatag': { name: 'metatag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MetaTagUnion'; ofType: null; }; }; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'translations': { name: 'translations'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Translation'; ofType: null; }; }; }; } }; }; };
    'MediaInterface': { kind: 'INTERFACE'; name: 'MediaInterface'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'changed': { name: 'changed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'metatag': { name: 'metatag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MetaTagUnion'; ofType: null; }; }; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; possibleTypes: 'MediaImage' | 'MediaDocument' | 'MediaRemoteVideo' | 'MediaVideo' | 'MediaAudio'; };
    'Link': { kind: 'OBJECT'; name: 'Link'; fields: { 'title': { name: 'title'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'url': { name: 'url'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'internal': { name: 'internal'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'ParagraphFormattedText': { kind: 'OBJECT'; name: 'ParagraphFormattedText'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'formattedText': { name: 'formattedText'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Text'; ofType: null; }; } }; 'heading': { name: 'heading'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'ParagraphImage': { kind: 'OBJECT'; name: 'ParagraphImage'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'image': { name: 'image'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaImage'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'ParagraphLink': { kind: 'OBJECT'; name: 'ParagraphLink'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'links': { name: 'links'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Link'; ofType: null; }; }; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'ParagraphAccordion': { kind: 'OBJECT'; name: 'ParagraphAccordion'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'accordionItems': { name: 'accordionItems'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ParagraphAccordionItem'; ofType: null; }; }; }; } }; 'accordionLayout': { name: 'accordionLayout'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'formattedText': { name: 'formattedText'; type: { kind: 'OBJECT'; name: 'Text'; ofType: null; } }; 'heading': { name: 'heading'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'primaryLink': { name: 'primaryLink'; type: { kind: 'OBJECT'; name: 'Link'; ofType: null; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'ParagraphAccordionItem': { kind: 'OBJECT'; name: 'ParagraphAccordionItem'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'contentElements': { name: 'contentElements'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'ParagraphAccordionItemContentElementsUnion'; ofType: null; }; }; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'formattedText': { name: 'formattedText'; type: { kind: 'OBJECT'; name: 'Text'; ofType: null; } }; 'heading': { name: 'heading'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'ParagraphAccordionItemContentElementsUnion': { kind: 'UNION'; name: 'ParagraphAccordionItemContentElementsUnion'; fields: {}; possibleTypes: 'ParagraphFormattedText' | 'ParagraphImage' | 'ParagraphLink' | 'ParagraphFileAttachment' | 'ParagraphVideo'; };
    'ParagraphFileAttachment': { kind: 'OBJECT'; name: 'ParagraphFileAttachment'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'fileAttachments': { name: 'fileAttachments'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaDocument'; ofType: null; }; }; }; } }; 'formattedText': { name: 'formattedText'; type: { kind: 'OBJECT'; name: 'Text'; ofType: null; } }; 'heading': { name: 'heading'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'MediaDocument': { kind: 'OBJECT'; name: 'MediaDocument'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'changed': { name: 'changed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'mediaDocument': { name: 'mediaDocument'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'File'; ofType: null; }; } }; 'metatag': { name: 'metatag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MetaTagUnion'; ofType: null; }; }; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'translations': { name: 'translations'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Translation'; ofType: null; }; }; }; } }; }; };
    'File': { kind: 'OBJECT'; name: 'File'; fields: { 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'url': { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'size': { name: 'size'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'mime': { name: 'mime'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'ParagraphVideo': { kind: 'OBJECT'; name: 'ParagraphVideo'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'video': { name: 'video'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'ParagraphVideoVideoUnion'; ofType: null; }; } }; }; };
    'ParagraphVideoVideoUnion': { kind: 'UNION'; name: 'ParagraphVideoVideoUnion'; fields: {}; possibleTypes: 'MediaRemoteVideo' | 'MediaVideo'; };
    'MediaRemoteVideo': { kind: 'OBJECT'; name: 'MediaRemoteVideo'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'changed': { name: 'changed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'mediaOembedVideo': { name: 'mediaOembedVideo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'metatag': { name: 'metatag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MetaTagUnion'; ofType: null; }; }; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'translations': { name: 'translations'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Translation'; ofType: null; }; }; }; } }; }; };
    'MediaVideo': { kind: 'OBJECT'; name: 'MediaVideo'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'changed': { name: 'changed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'mediaVideoFile': { name: 'mediaVideoFile'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'File'; ofType: null; }; } }; 'metatag': { name: 'metatag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MetaTagUnion'; ofType: null; }; }; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'translations': { name: 'translations'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Translation'; ofType: null; }; }; }; } }; }; };
    'ParagraphListingArticle': { kind: 'OBJECT'; name: 'ParagraphListingArticle'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'heading': { name: 'heading'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'limit': { name: 'limit'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'NodePage': { kind: 'OBJECT'; name: 'NodePage'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'author': { name: 'author'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; 'changed': { name: 'changed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'contentElements': { name: 'contentElements'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'NodePageContentElementsUnion'; ofType: null; }; }; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'excerpt': { name: 'excerpt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'image': { name: 'image'; type: { kind: 'OBJECT'; name: 'Image'; ofType: null; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'metatag': { name: 'metatag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MetaTagUnion'; ofType: null; }; }; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'promote': { name: 'promote'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'sticky': { name: 'sticky'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'title': { name: 'title'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'translations': { name: 'translations'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Translation'; ofType: null; }; }; }; } }; }; };
    'NodePageContentElementsUnion': { kind: 'UNION'; name: 'NodePageContentElementsUnion'; fields: {}; possibleTypes: 'ParagraphHero' | 'ParagraphFormattedText' | 'ParagraphImage' | 'ParagraphAccordion' | 'ParagraphLink' | 'ParagraphVideo' | 'ParagraphListingArticle' | 'ParagraphFileAttachment'; };
    'MediaUnion': { kind: 'UNION'; name: 'MediaUnion'; fields: {}; possibleTypes: 'MediaAudio' | 'MediaDocument' | 'MediaImage' | 'MediaRemoteVideo' | 'MediaVideo'; };
    'MediaAudio': { kind: 'OBJECT'; name: 'MediaAudio'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'changed': { name: 'changed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'created': { name: 'created'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'mediaAudioFile': { name: 'mediaAudioFile'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'File'; ofType: null; }; } }; 'metatag': { name: 'metatag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MetaTagUnion'; ofType: null; }; }; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'translations': { name: 'translations'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Translation'; ofType: null; }; }; }; } }; }; };
    'MenuAvailable': { kind: 'ENUM'; name: 'MenuAvailable'; type: 'FOOTER' | 'MAIN'; };
    'Menu': { kind: 'OBJECT'; name: 'Menu'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'items': { name: 'items'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MenuItem'; ofType: null; }; }; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'MenuInterface': { kind: 'INTERFACE'; name: 'MenuInterface'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'uuid': { name: 'uuid'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'items': { name: 'items'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MenuItem'; ofType: null; }; }; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; possibleTypes: 'Menu'; };
    'MenuItem': { kind: 'OBJECT'; name: 'MenuItem'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'title': { name: 'title'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'url': { name: 'url'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'langcode': { name: 'langcode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Language'; ofType: null; }; } }; 'internal': { name: 'internal'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'expanded': { name: 'expanded'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'attributes': { name: 'attributes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MenuItemAttributes'; ofType: null; }; } }; 'children': { name: 'children'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MenuItem'; ofType: null; }; }; }; } }; 'route': { name: 'route'; type: { kind: 'UNION'; name: 'RouteUnion'; ofType: null; } }; }; };
    'MenuItemAttributes': { kind: 'OBJECT'; name: 'MenuItemAttributes'; fields: { 'class': { name: 'class'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'icon': { name: 'icon'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'RouteUnion': { kind: 'UNION'; name: 'RouteUnion'; fields: {}; possibleTypes: 'RouteInternal' | 'RouteExternal' | 'RouteRedirect'; };
    'RouteInternal': { kind: 'OBJECT'; name: 'RouteInternal'; fields: { 'url': { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'internal': { name: 'internal'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'breadcrumbs': { name: 'breadcrumbs'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Link'; ofType: null; }; }; } }; 'entity': { name: 'entity'; type: { kind: 'UNION'; name: 'RouteEntityUnion'; ofType: null; } }; }; };
    'Route': { kind: 'INTERFACE'; name: 'Route'; fields: { 'url': { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'internal': { name: 'internal'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; possibleTypes: 'RouteInternal' | 'RouteExternal' | 'RouteRedirect'; };
    'RouteEntityUnion': { kind: 'UNION'; name: 'RouteEntityUnion'; fields: {}; possibleTypes: 'NodeArticle' | 'NodeFrontpage' | 'NodePage'; };
    'RouteExternal': { kind: 'OBJECT'; name: 'RouteExternal'; fields: { 'url': { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'internal': { name: 'internal'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'RouteRedirect': { kind: 'OBJECT'; name: 'RouteRedirect'; fields: { 'url': { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'internal': { name: 'internal'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'redirect': { name: 'redirect'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'Cursor': unknown;
    'ConnectionSortKeys': { kind: 'ENUM'; name: 'ConnectionSortKeys'; type: 'CREATED_AT' | 'UPDATED_AT' | 'TITLE' | 'STICKY' | 'PROMOTED'; };
    'NodeArticleConnection': { kind: 'OBJECT'; name: 'NodeArticleConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NodeArticleEdge'; ofType: null; }; }; }; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NodeArticle'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ConnectionPageInfo'; ofType: null; }; } }; }; };
    'Connection': { kind: 'INTERFACE'; name: 'Connection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INTERFACE'; name: 'Edge'; ofType: null; }; }; }; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INTERFACE'; name: 'EdgeNode'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ConnectionPageInfo'; ofType: null; }; } }; }; possibleTypes: 'NodeArticleConnection' | 'NodePageConnection' | 'MediaAudioConnection' | 'MediaDocumentConnection' | 'MediaImageConnection' | 'MediaRemoteVideoConnection' | 'MediaVideoConnection'; };
    'Edge': { kind: 'INTERFACE'; name: 'Edge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Cursor'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INTERFACE'; name: 'EdgeNode'; ofType: null; }; } }; }; possibleTypes: 'NodeArticleEdge' | 'NodePageEdge' | 'MediaAudioEdge' | 'MediaDocumentEdge' | 'MediaImageEdge' | 'MediaRemoteVideoEdge' | 'MediaVideoEdge'; };
    'ConnectionPageInfo': { kind: 'OBJECT'; name: 'ConnectionPageInfo'; fields: { 'hasNextPage': { name: 'hasNextPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'hasPreviousPage': { name: 'hasPreviousPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'startCursor': { name: 'startCursor'; type: { kind: 'SCALAR'; name: 'Cursor'; ofType: null; } }; 'endCursor': { name: 'endCursor'; type: { kind: 'SCALAR'; name: 'Cursor'; ofType: null; } }; }; };
    'NodeArticleEdge': { kind: 'OBJECT'; name: 'NodeArticleEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Cursor'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NodeArticle'; ofType: null; }; } }; }; };
    'NodePageConnection': { kind: 'OBJECT'; name: 'NodePageConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NodePageEdge'; ofType: null; }; }; }; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NodePage'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ConnectionPageInfo'; ofType: null; }; } }; }; };
    'NodePageEdge': { kind: 'OBJECT'; name: 'NodePageEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Cursor'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NodePage'; ofType: null; }; } }; }; };
    'MediaAudioConnection': { kind: 'OBJECT'; name: 'MediaAudioConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaAudioEdge'; ofType: null; }; }; }; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaAudio'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ConnectionPageInfo'; ofType: null; }; } }; }; };
    'MediaAudioEdge': { kind: 'OBJECT'; name: 'MediaAudioEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Cursor'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaAudio'; ofType: null; }; } }; }; };
    'MediaDocumentConnection': { kind: 'OBJECT'; name: 'MediaDocumentConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaDocumentEdge'; ofType: null; }; }; }; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaDocument'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ConnectionPageInfo'; ofType: null; }; } }; }; };
    'MediaDocumentEdge': { kind: 'OBJECT'; name: 'MediaDocumentEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Cursor'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaDocument'; ofType: null; }; } }; }; };
    'MediaImageConnection': { kind: 'OBJECT'; name: 'MediaImageConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaImageEdge'; ofType: null; }; }; }; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaImage'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ConnectionPageInfo'; ofType: null; }; } }; }; };
    'MediaImageEdge': { kind: 'OBJECT'; name: 'MediaImageEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Cursor'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaImage'; ofType: null; }; } }; }; };
    'MediaRemoteVideoConnection': { kind: 'OBJECT'; name: 'MediaRemoteVideoConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaRemoteVideoEdge'; ofType: null; }; }; }; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaRemoteVideo'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ConnectionPageInfo'; ofType: null; }; } }; }; };
    'MediaRemoteVideoEdge': { kind: 'OBJECT'; name: 'MediaRemoteVideoEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Cursor'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaRemoteVideo'; ofType: null; }; } }; }; };
    'MediaVideoConnection': { kind: 'OBJECT'; name: 'MediaVideoConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaVideoEdge'; ofType: null; }; }; }; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaVideo'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ConnectionPageInfo'; ofType: null; }; } }; }; };
    'MediaVideoEdge': { kind: 'OBJECT'; name: 'MediaVideoEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Cursor'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaVideo'; ofType: null; }; } }; }; };
    'SortDirection': { kind: 'ENUM'; name: 'SortDirection'; type: 'ASC' | 'DESC'; };
    'ArticlesViewFilterInput': { kind: 'INPUT_OBJECT'; name: 'ArticlesViewFilterInput'; inputFields: [{ name: 'sticky'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: 'langcode'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'ArticlesViewResult': { kind: 'OBJECT'; name: 'ArticlesViewResult'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'view': { name: 'view'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'display': { name: 'display'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'label': { name: 'label'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ViewPageInfo'; ofType: null; }; } }; 'results': { name: 'results'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'NodeUnion'; ofType: null; }; }; }; } }; }; };
    'View': { kind: 'INTERFACE'; name: 'View'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'view': { name: 'view'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'display': { name: 'display'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'langcode': { name: 'langcode'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'label': { name: 'label'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ViewPageInfo'; ofType: null; }; } }; }; possibleTypes: 'ArticlesViewResult'; };
    'ViewPageInfo': { kind: 'OBJECT'; name: 'ViewPageInfo'; fields: { 'offset': { name: 'offset'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'page': { name: 'page'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'pageSize': { name: 'pageSize'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'total': { name: 'total'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { '_': { name: '_'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'Float': unknown;
    'DateRange': { kind: 'OBJECT'; name: 'DateRange'; fields: { 'start': { name: 'start'; type: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; } }; 'end': { name: 'end'; type: { kind: 'OBJECT'; name: 'DateTime'; ofType: null; } }; }; };
    'KeyValueInput': { kind: 'INPUT_OBJECT'; name: 'KeyValueInput'; inputFields: [{ name: 'key'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'value'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'MenuUnion': { kind: 'UNION'; name: 'MenuUnion'; fields: {}; possibleTypes: 'Menu'; };
    'ParagraphUnion': { kind: 'UNION'; name: 'ParagraphUnion'; fields: {}; possibleTypes: 'ParagraphAccordion' | 'ParagraphAccordionItem' | 'ParagraphFileAttachment' | 'ParagraphFormattedText' | 'ParagraphHero' | 'ParagraphImage' | 'ParagraphLink' | 'ParagraphListingArticle' | 'ParagraphVideo'; };
    'PhoneNumber': unknown;
    'UntypedStructuredData': unknown;
    'UserUnion': { kind: 'UNION'; name: 'UserUnion'; fields: {}; possibleTypes: 'User'; };
    'ViewReference': { kind: 'OBJECT'; name: 'ViewReference'; fields: { 'view': { name: 'view'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'display': { name: 'display'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'contextualFilter': { name: 'contextualFilter'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; } }; 'pageSize': { name: 'pageSize'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'query': { name: 'query'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'ViewResultUnion': { kind: 'UNION'; name: 'ViewResultUnion'; fields: {}; possibleTypes: 'ArticlesViewResult'; };
    '_': unknown;
  };
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}