# An example recipe that shows the creation of a user role.
name: 'Wunder next setup'
description: "Enable needed modules to use next-drupal and add pathauto setup"
type: 'Setup'
recipes:
  - wunder_pages
  - wunder_search
install:
  - next
  - next_jsonapi
  - pathauto
  - wunder_next
  - jsonapi_menu_items
  - redirect
  - require_login
  - webform_rest
config:
  import:
    redirect: '*'
  actions:
    system.site:
      simple_config_update:
        page.front: '/admin/content'
    user.role.anonymous:
      ensure_exists:
        label: 'Anonymous user'
      grantPermissions:
        - 'restful post webform_rest_submit'
