import "@/styles/globals.css";

import { notFound } from "next/navigation";

import { Footer } from "@/components/footer/footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// Can be imported from a shared config
const locales = ["en", "fi", "sv"];

interface LayoutProps {
  params: {
    locale: string;
  };
  children: React.ReactNode;
}

export default function Layout({ children, params: { locale } }: LayoutProps) {
  // Validate that the incoming `locale` parameter is valid
  if (!locales.includes(locale)) notFound();

  return (
    <html lang={locale}>
      <body>
        <div className="flex min-h-screen flex-col">
          {/* <Header menu={menus.main} /> */}
          <main className="grow bg-mischka" id="main-content">
            <div className="mx-auto max-w-6xl px-6 py-8">{children}</div>
          </main>
          <Footer locale={locale} />
        </div>
      </body>
    </html>
  );
}
