import { notFound } from "next/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// Can be imported from a shared config
const locales = ["en", "fi", "sv"];

interface LocaleLayoutProps {
  params: {
    locale: string;
  };
  children: React.ReactNode;
}

export default function LocaleLayout({
  children,
  params: { locale },
}: LocaleLayoutProps) {
  // Validate that the incoming `locale` parameter is valid
  if (!locales.includes(locale)) notFound();

  return (
    <html lang={locale}>
      <body>{children}</body>
    </html>
  );
}
