# A recipe that sets up the basic language setup for a site.
name: 'Wunder languages'
description: "A recipe to set up basic language setup for a site."
type: 'Configuration'
recipes:
  - wunder_base
install:
  - language
  - config_translation
  - content_translation
  - locale
  - file
  - tour
config:
  import:
    language: '*'
    config_translation: '*'
    content_translation: '*'
